### ISSUE TITLE
Internal SASS Stylesheets

### ISSUE THREAD

**Issue by intellix** [dlmanning/gulp-sass#198]
So I'm creating an SPA and have created an awesome CSS-only loader, which will be within index.html internally so it's displayed before any requests have been made... you know like:

**index.html**
```css
<style type="text/css">
    [ng-cloak] > * { display: none; }
    [ng-cloak] > .loader {
        position: absolute; top: 0; right: 0; bottom: 0; left: 0;
        background: #000;
        // Some cool loader
    }
    </style>
```

The loader I've created is pretty clever and I'm using the magic of SASS variables, Math etc. I'd like to include it within my build process and I think it would be awesome if I could:

**index.html**
```css
<style type="text/scss">
    $variable1: #F2C000;
    $variable2: #0a74ac;
    @import 'styles/loader';
</style>
```

You would point gulp-sass at HTML files, it would find text/scss and compile the block. Awesome right? Is there functionality already elsewhere, does it belong here or am I crazy?
