### ISSUE TITLE
unexpected blank space added

### ISSUE THREAD

**Issue by VaJoy** [dlmanning/gulp-sass#242]
the original code as
```scss
@mixin pTransition($content){
  -webkit-transition:-webkit-$content;
  -moz-transition:-moz-$content;
  -ms-transition:-ms-$content;
}
@include pTransition(transform .3s);
```
and it has been compiled to
```scss
  -webkit-transition:-webkit- transform .3s; //a blank space between '-webkit-' and 'transform'
  -moz-transition:-moz- transform .3s;
  -ms-transition:-ms- transform .3s;
```
it`s weird that a blank space was inserted after the prefix like `-webkit-`
any method to solve my problem?
