### ISSUE TITLE
@extend doesn't work with nested selectors

### ISSUE THREAD

**Issue by nmec** [dlmanning/gulp-sass#29]
Input:

``` scss
%menu {

    background: black;

    ul {
        padding: 0;
        margin: 0;
    }

    li {
        list-style: none;
        padding: 0;
        margin: 0;
    }

    a {
        text-decoration: none;
    }
}

.main-menu {
    @extend %menu;
    background: lightgrey;
    width: 100%;
}
```

Expected:

``` css
.main-menu {
  background: black; }
  .main-menu ul {
    padding: 0;
    margin: 0; }
  .main-menu li {
    list-style: none;
    padding: 0;
    margin: 0; }
  .main-menu a {
    text-decoration: none; }

.main-menu {
  background: lightgrey;
  width: 100%; }
```

Actual output:

``` css
.main-menu {
  background: black; }
  %menu ul {
    padding: 0;
    margin: 0; }
  %menu li {
    list-style: none;
    padding: 0;
    margin: 0; }
  %menu a {
    text-decoration: none; }

.main-menu {
  background: lightgrey;
  width: 100%; }
```

The same happens when you use actual classes instead of placeholders.
