### ISSUE TITLE
npm gulp-sass Variables and Mixins Not Working from @import

### ISSUE THREAD

**Issue by isz92tashkent** [dlmanning/gulp-sass#313]

**Comment by felipepastor** [comment]
Same here. I'm developing an ionic project and i need to use some compass mixin. Is there a way to use it?

Thanks.

**Comment by renarsvilnis** [comment]
+1 

Providing an example.
*Using gulp-sass v2.0.4*

`site.scss` - main file that just imports files:
```scss
@import 'utils/mixins';
@import 'pages/home';
```

`utils/_mixins.scss`:
```scss
.v_home {
  @include vertical-align;
}
```

`pages/_home.scss`:
```scss
@mixin vertical-align {
  position: relative;
  top: 50%;
  transform: translateY(-50%);
}
```

But when compiling i get an error message: 
```
Error in plugin 'sass'
Message:
    src/scss/pages/home.scss
  7:12  no mixin named vertical-align
```
