### ISSUE TITLE
Calc function breaks generation file process

### ISSUE THREAD

**Issue by lucasljj** [dlmanning/gulp-sass#422]
<h5>Code to reproduce the error:</h5>
```css
.full-block {
    width: call(100% - 16px);
}
```
<h5>Errorr:</h5>
Error in plugin 'sass'  (***gulp-sass***)
Message:
    css/myscssfile.scss
Error: Incompatible units: 'px' and '%'.
        on line 2 of stdin
\>\>   width: call(100% - 16px);

<h5>Versions of packages & system info:</h5>
node: v4.0.0,
nodejs: v0.12.9,
gulp: 3.9.0,
gulp-sass: 2.1.1,
OS: Ubuntu 14.04.3
