### ISSUE TITLE
& close after selector don't work

### ISSUE THREAD

**Issue by dchuangincar** [dlmanning/gulp-sass#424]
```css
.btn {
    .open .dropdown-toggle& {
        color: #000;
    }
}
```
the code above just generate:
```css
.btn, .open .dropdown-toggle& {
    color: #000;
}
