### ISSUE TITLE
Parent selector exits gulp with error code

### ISSUE THREAD

**Issue by ianschmitz** [dlmanning/gulp-sass#477]
I'm using the latest version of gulp-sass (2.3.1) and am having issues with one of my scss files. The issue has started unexpectedly without me modifying the .scss files. I've tried clearing the node_modules folder and doing a fresh `npm install` with no luck.

I have a specific selector that causes error message:
`The command "gulp" exited with code -1073741819`

gulp-sass did not emit any error message like it normally does when there's a syntax error or missing variable etc.

I was able to narrow it down to a specific ampersand parent selector:

```css
a:not(.btn):not(.btn-large):not(.btn-floating) {
            color: blue;
            margin-right: 1px;
            transition: color .3s ease;
            text-transform: uppercase;

            &:hover {
                color: red;
            }
}
```

If i remove the parent selector, gulp-sass compiles with no errors. I use the ampersand selector in many other places, but this example is the only one that causes gulp to crash. I've tried debugging using node-debug, but wasn't able to get anything useful out of it.
