### ISSUE TITLE
Module error

### ISSUE THREAD

**Issue by edj-boston** [dlmanning/gulp-sass#59]
Hi, I get this error from your module:

``` sh
[gulp] Starting 'styles'...

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
[gulp] Error in plugin 'gulp-sass': source string:54: error: property "solid" must be followed by a ':'

    at opts.error (/Users/ejohnson/Git/matchstickjs.com/node_modules/gulp-sass/index.js:67:17)
    at onError (/Users/ejohnson/Git/matchstickjs.com/node_modules/gulp-sass/node_modules/node-sass/sass.js:72:16)
```

Here's my task:

``` js
// Minify and combine all CSS
gulp.task('styles', ['clean'], function() {
    return gulp.src([
        'assets/scss/*.scss'
        'assets/bower/bootstrap/dist/css/bootstrap.css',
        'assets/bower/fontawesome/css/font-awesome.css'
    ]).pipe(gulpif(/[.]scss$/, sass()))
        .pipe(minify())
        .pipe(concat('all.min.css'))
        .pipe(gulp.dest('build/css'));
});
```

Here's my SCSS (I haven't converted it to SASS yet because I can't get this working

``` css
/*!
 *  Custom Styles
 */

/* Color pallete
@dark-gray:   #777777;
@orange:      #ee7733;
@orange-dark: #cc6633;
@tan:         #ffffee;
@light-gray:  #ddddcc;
@peach:       #eeccaa;
*/

/* Fonts */
@font-face {
    font-family: 'Open-Sans';
    src: url('/fonts/Open-Sans.eot');
    src:
        url('/fonts/Open-Sans.eot?#iefix') format('embedded-opentype'),
        url('/fonts/Open-Sans.woff') format('woff'),
        url('/fonts/Open-Sans.ttf') format('truetype');
}

@font-face {
    font-family: 'SourceCodePro';
    src: url('/fonts/SourceCodePro.eot');
    src:
        url('/fonts/SourceCodePro.eot?#iefix') format('embedded-opentype'),
        url('/fonts/SourceCodePro.woff') format('woff'),
        url('/fonts/SourceCodePro.ttf') format('truetype');
}

@font-face {
    font-family: 'Merriweather';
    src: url('/fonts/Merriweather.eot');
    src:
        url('/fonts/Merriweather.eot?#iefix') format('embedded-opentype'),
        url('/fonts/Merriweather.woff') format('woff'),
        url('/fonts/Merriweather.ttf') format('truetype');
}

/* Base styles */
* { font-family:'Merriweather'; }
html, body { margin:0; padding:0; background:#ee7733 url('/img/bg.png'); }
a { color:#ee7733; }
a:hover { color:#cc6633; text-decoration:underline; }
pre code { font-family:'SourceCodePro'; border:0; }
code { font-family:'SourceCodePro'; color:#ee7733; background-color:#f5f5f5; border:1px solid #ccc; }
.container { padding:20px; background-color:#ffffee; }

/* Header */
header { color:#777; }
#links { text-align:center;  }
#links ul { list-style:none; margin:0; padding:0; font-size:1.1em; }
#links ul li { display:inline-block; margin:0 0.5em; line-height:1.5em; }
#links ul li small { font-size:1.1em; }

/* Share buttons */
ul#share { list-style:none; text-align:center; margin-top:2em; }
ul#share li { display:inline-block; }

/* Main Section */
main.container { color:#000; padding-top:0; }
h1 { text-align:center; margin-top:0; }
h1#page-not-found { margin-top:2em; }
h2, h3 { font-family:'Open-Sans',sans-serif; }
h2 { background-color:#777; solid #000; color:#fff; padding:10px 35px; margin-top:40px; margin-left:-35px; margin-right:-20px; position:relative; }
h2:after { content:""; display:block; color:#fff; bottom:-15px; left:0; position:absolute;
        width: 0; z-index:0; height: 0; 
        border-bottom:15px solid transparent;
        border-right:15px solid #333; }
h3 { margin-top:28px; font-weight:bold; }
h4 { margin-top:28px; font-weight:bold; }

/* Footer */
footer { text-align:center; color:#777; border-top:dashed 1px #ccc; margin:auto 1em; }

/* Media Queries */
@media (min-width: 1200px) {
    .container { max-width:750px; }
}
```

Any help is appreciated. Thanks!
