### ISSUE TITLE
Sass extend into placeholders swallow other selectors

### ISSUE THREAD

**Issue by kleinfreund** [dlmanning/gulp-sass#65]
**Steps to reproduce:**

``` scss
.clearfix:after,
%clearfix:after {
    content: "";
    display: table;
    clear: both;
}

.site-nav {
    @extend %clearfix;
}
```

**Expected output:**

``` css
.clearfix:after, .site-nav:after {
    content: "";
    display: table;
    clear: both; }
```

**Actual output:**

``` css
.site-nav:after {
    content: "";
    display: table;
    clear: both; }
```

I tested if it works with `sass sass/main.scss css/test.css` and it does.
- gulp-sass v0.7.2
- sass v3.3.9
