### ISSUE TITLE
Error when using CSS3's var() in rgba()

### ISSUE THREAD

**Issue by philSixZero** [dlmanning/gulp-sass#658]
## Description
When calling rgba() and passing a CSS3 variable, gulp-sass results in an error:
```css
:root {
  --color: 0,0,0,.5; /* Black with an alpha of 50% */
}

div {
  border-color: rgba(var(--color)); /* CSS3 is able to do this, gulp-sass throws an error */
}
```
### Result
**Error:** overloaded function 'rgba' given wrong number of arguments

## Conclusion
Guess this is a :bug:
