### ISSUE TITLE
CSS Variables in color functions gives an error, but is correct in pure CSS

### ISSUE THREAD

**Issue by barcia** [dlmanning/gulp-sass#670]
If I try to put a CSS Variable (or Custom Property) in a color function gulp-sass gives me an error, but this is perfectly correct in pure CSS.

Sass solved this issue more than a year ago (https://github.com/sass/sass/pull/2207).

This is an example:
```scss
// style.scss
.foo {
    background-color: hsla(0, 0%, 0%, var(--opacity));
}
```

In CSS works, but gulp-sass return this: `Error: argument '$alpha' of 'hsla($hue, $saturation, $lightness, $alpha)' must be a number`

What is the problem? 🧐

Thanks
