### ISSUE TITLE
SCSS variables within single quotes not resolved with updated version of gulp-sass

### ISSUE THREAD

**Issue by ladvishal1985** [dlmanning/gulp-sass#675]
Hi Team,
With earlier version of gulp-sass i.e. 3.1.0 we used below syntax for declaring and resolving 
$layout-large: '(min-width : $bp-medium+1) and (max-width : $bp-large)';
@media #{$layout-large} 

Post upgrade with 3.2.1 this above variable are not resolved. We had to remove the quotes on variables to make it work correctly:
$layout-large: (min-width : $bp-medium+1) and (max-width : $bp-large);

Please let us know  if this is expected behaviour.

Thanks
Vishal

**Comment by xzyfer** [comment]
Please provide a complete example of scss code so that we can see this
issue for ourselves.

**Comment by ladvishal1985** [comment]
Sure we will provide the same

**Comment by xzyfer** [comment]
Tested with gulp-sass 3.2.1

```scss
$layout-large: '(min-width : $bp-medium+1) and (max-width : $bp-large)';

@media #{$layout-large} {
  a { b: c };
}
```

Produces
```css
@media (min-width: $bp-medium + 1) and (max-width: $bp-large) {
  a {
    b: c;
  }
}
```

**Comment by xzyfer** [comment]
Also
```scss
$bp-medium: 100;
$bp-large: 200;
$layout-large: '(min-width : #{$bp-medium}+1) and (max-width : #{$bp-large})';

@media #{$layout-large} {
  a { b: c };
}
```
Produces
```css
@media (min-width: 100 + 1) and (max-width: 200) {
  a {
    b: c;
  }
}
```
