### ISSUE TITLE
Compiles when there are error in SCSS code

### ISSUE THREAD

**Issue by neins** [dlmanning/gulp-sass#737]
When i was on gulp 3 everything was fine - on error occur, like type a plain text inside or outside CSS blocks {}, there was error handler gulp-plumber and message pop up with gulp-notify:
```javascript
gulp.task('sass', function () {
    return gulp.src(path.layout.sass)
    .pipe(plumber({errorHandler: notify.onError({
        message: "Error: <%= error.message %>",
        title: "SASS - ошибка компиляции"
      })}))
    .pipe(sass())
    .pipe(gulp.dest(path.layoutDest.css))
    .pipe(reload({stream: true}));
});
```
 Then i made my "big update" to gulp 4 and other packages in package.json, among which was gulp-sass (update from 4.0.1 to 4.0.2) and here the problems started... First there is no need to gulp-plumber, because gulp-plumber has stopped working and gulp 4 won't terminate when error occur (idk it's for everyone or only for me), ok. Having fiddled, I set up showing error messages. So my new task look like this:
```javascript
gulp.task('sass', function () {
    return gulp.src(path.layout.sass)
    .pipe(sass()
        .on('error', notify.onError({
            message: "Error: <%= error.message %>",
            title: "SASS - ошибка компиляции"
        })
    ))
    .pipe(gulp.dest(path.layoutDest.css))
    .pipe(reload({stream: true}));
});
```
But when i had a typo _outside_ the block there is nothing happend, i mean sass has continue compile without appear any error, for example:
```scss
//SCSS

typo   //hmm, it's ok, let's break the layout

.soc {
  typo   //an error was detected
  display: flex;
  padding-left: 15px;
}
```
Thus my layout has crashing in place where the typo was between the blocks. Does anyone have a similar problem?
___
I would like to complement my problem with an example - how it compiles to css:

```scss
//SCSS

TYPO

.burger {
  margin-right: 15px;
  cursor: pointer;
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 2;
  &:hover {
    background-color: #E3CD56;
  }
  &:active {
    background-color: #DBAA35;
    transition: none;
  }
}
```

```css
//CSS

TYPO
.burger {
  margin-right: 15px;
  cursor: pointer;
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 2; }
  TYPO
.burger:hover {
    background-color: #E3CD56; }
  TYPO
.burger:active {
    background-color: #DBAA35;
    transition: none; }
```

**Comment by neins** [comment]
I would like to complement my problem with an example - how it compiles to css:

```scss
//SCSS

TYPO

.burger {
  margin-right: 15px;
  cursor: pointer;
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 2;
  &:hover {
    background-color: #E3CD56;
  }
  &:active {
    background-color: #DBAA35;
    transition: none;
  }
}
```

```css
//CSS

TYPO
.burger {
  margin-right: 15px;
  cursor: pointer;
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 2; }
  TYPO
.burger:hover {
    background-color: #E3CD56; }
  TYPO
.burger:active {
    background-color: #DBAA35;
    transition: none; }
```
