### ISSUE TITLE
Single-line comment swallows every subsequent line

### ISSUE THREAD

**Issue by afoeder** [dlmanning/gulp-sass#82]
I did not manage to narrow down whether it's the plugin itself or node-sass, but if I have something like this in my .scss,

```css
body { line-height: 1; }
// this is a single line comment
p { color: red; }
```

the output is only

```css
body { line-height: 1; }
```

I could imagine that somehow the whole SCSS is treated as a single line; that would explain what I experienced.

Is that possible, or can you confirm that, or do you have ideas?
